name: CICD

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: batoolshaheen/nodejs:latest

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull image from docker hub
        run: docker pull integrationninjas/nodejs:latest
      - name: Delete old container
        run: docker rm -f nodejs-container
      - name: Run docker container
        run: docker run -d -p 3000:3000 --name nodejs-container integrationninjas/nodejs        